# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements-dev.txt .

# Install any needed packages specified in requirements-dev.txt
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy the integration tests directory into the container at /app
COPY ./integration_tests ./integration_tests

# Set the default command to run when the container starts
# This will execute pytest against the tests in the integration_tests directory
CMD ["pytest", "/app/integration_tests"]
