"""Change Cell.tool_call_id type from UUID to String

Revision ID: 23e0b8b30c1e
Revises: d3b0a9c8e1f7
Create Date: 2025-05-02 08:16:14.081954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23e0b8b30c1e'
down_revision: Union[str, None] = 'd3b0a9c8e1f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells', schema=None) as batch_op:
        batch_op.alter_column('tool_call_id',
                   existing_type=sa.NUMERIC(),
                   type_=sa.String(length=36),
                   existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells', schema=None) as batch_op:
        batch_op.alter_column('tool_call_id',
                   existing_type=sa.String(length=36),
                   type_=sa.NUMERIC(),
                   existing_nullable=False)
    # ### end Alembic commands ###
